# Generated by Django 6.0 on 2025-12-17 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
