# Generated by Django 6.0 on 2025-12-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='fullname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
