# Generated by Django 6.0 on 2025-12-23 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_fullname_pendinguser_fullname'),
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='orders.order'),
        ),
    ]
