# Generated by Django 6.0 on 2025-12-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_product_productimage_productvariant_cartitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='prodict',
            new_name='product',
        ),
    ]
